"""Generate markdown tables from saved results. No hand-copied numbers.

    uv run python bench/make_tables.py

Reads results/search/**/*.json and results/micro/*.json and writes results/tables.md.
For each configuration (see records.config_key) only the newest result is shown.
"""

from __future__ import annotations

import json
from typing import Any

from benchmeta import REPO_ROOT
from records import latest_records, load_records

RESULTS = REPO_ROOT / "results"


def fmt(summary: dict[str, float], digits: int) -> str:
    return f"{summary['mean']:.{digits}f} ± {summary['stdev']:.{digits}f}"


def machine(record: dict[str, Any]) -> str:
    return record["hardware"].get("cpu") or record["hardware"]["machine"]


def search_table() -> list[str]:
    records = latest_records(load_records())
    if not records:
        return []
    lines = [
        "## Search",
        "",
        "| Dataset | Library | Index | Build params | Search params | Machine | Threads | Runs "
        "| Recall@k | Recall@k by id | QPS | p50 µs | p99 µs | Build s | Commit |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in sorted(records, key=lambda r: (r["dataset"]["name"], r["library"], r["index"])):
        build = ", ".join(f"{k}={v}" for k, v in r["build_params"].items()) or "—"
        commit = r["git"]["commit"][:8] + ("*" if r["git"]["dirty"] else "")
        for point in r["points"]:
            s = point["summary"]
            search = ", ".join(f"{k}={v}" for k, v in point["search_params"].items()) or "—"
            lines.append(
                f"| {r['dataset']['name']} | {r['library']} | {r['index']} | {build} | {search} "
                f"| {machine(r)} | {r['threads']} | {len(point['runs'])} "
                f"| {s['recall']['mean']:.4f} (k={r['k']}) | {s['recall_by_id']['mean']:.4f} "
                f"| {fmt(s['qps'], 1)} | {fmt(s['latency_p50_us'], 1)} "
                f"| {fmt(s['latency_p99_us'], 1)} | {r['build_seconds']:.2f} | `{commit}` |"
            )
    notes = [
        "",
        "Recall@k is tie-aware (ann-benchmarks definition): a result counts if it is no farther",
        "than the k-th true neighbor. Recall by id is strict id matching; it can be lower when",
        "several vectors tie at the k-th distance. hnswlib/FAISS latencies include Python call",
        "overhead (their QPS does not). `*` = uncommitted changes when measured.",
        "",
    ]
    return lines + notes


def micro_table() -> list[str]:
    records = [json.loads(p.read_text()) for p in sorted(RESULTS.glob("micro/*.json"))]
    if not records:
        return []
    lines = [
        "## Microbenchmarks",
        "",
        "| Benchmark | Machine | ns/op (mean ± stdev) | Commit |",
        "|---|---|---|---|",
    ]
    rows: dict[tuple[str, str], str] = {}
    for record in sorted(records, key=lambda r: r["timestamp"]):
        benches = record["benchmark"]["benchmarks"]
        stats = {
            (b["run_name"], b["aggregate_name"]): b["cpu_time"]
            for b in benches
            if b.get("run_type") == "aggregate"
        }
        commit = record["git"]["commit"][:8] + ("*" if record["git"]["dirty"] else "")
        for (name, agg), mean in stats.items():
            if agg != "mean":
                continue
            stdev = stats.get((name, "stddev"), 0.0)
            rows[(name, machine(record))] = (
                f"| {name} | {machine(record)} | {mean:.2f} ± {stdev:.2f} | `{commit}` |"
            )
    return [*lines, *(rows[key] for key in sorted(rows)), ""]


def main() -> int:
    body = ["# Results", "", "Generated by `bench/make_tables.py`. Do not edit by hand.", ""]
    body += search_table() + micro_table()
    out = RESULTS / "tables.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(body))
    print(f"wrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
