"""Plot recall@k vs QPS curves (ann-benchmarks style) from saved result records.

    uv run python bench/plot_recall_qps.py

Writes results/plots/recall_qps_<dataset>.png: one chart per dataset, one line per configuration
(latest record wins), QPS on a log scale, error bars = stdev across runs. The same numbers are in
results/tables.md.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from benchmeta import REPO_ROOT, hardware_note, is_development_machine
from records import latest_records, load_records

# Validated categorical palette (dataviz reference, light surface), assigned per entity so a
# library keeps its color whatever else is plotted. Markers are a second, non-color encoding.
STYLES: dict[tuple[str, str], tuple[str, str]] = {
    ("strata", "hnsw"): ("#2a78d6", "o"),
    ("hnswlib", "hnsw"): ("#eb6834", "s"),
    ("faiss", "hnsw"): ("#1baf7a", "^"),
    ("strata", "brute_force"): ("#eda100", "D"),
    ("faiss", "flat"): ("#e87ba4", "v"),
    ("strata", "pq"): ("#008300", "P"),
}
SURFACE = "#fcfcfb"
TEXT = "#0b0b0b"
MUTED = "#52514e"


def label(record: dict[str, Any]) -> str:
    params = ", ".join(f"{k}={v}" for k, v in record["build_params"].items())
    name = f"{record['library']} {record['index'].replace('_', ' ')}"
    return f"{name} ({params})" if params else name


def plot_dataset(
    dataset: str,
    records: list[dict[str, Any]],
    out: Path | None = None,
    note: str | None = None,
    source: str = "bench/plot_recall_qps.py",
    title_suffix: str | None = None,
) -> str:
    """One recall-vs-QPS chart. out defaults to results/plots/recall_qps_<dataset>.png; note is
    printed bottom left (e.g. how to read QPS from this machine); title_suffix is appended to
    the title (e.g. marking development results)."""
    fig, ax = plt.subplots(figsize=(8, 5.5), dpi=150)
    fig.patch.set_facecolor(SURFACE)
    ax.set_facecolor(SURFACE)

    k = records[0]["k"]
    for record in sorted(records, key=label):
        color, marker = STYLES.get((record["library"], record["index"]), (MUTED, "x"))
        points = sorted(record["points"], key=lambda p: p["summary"]["recall"]["mean"])
        xs = [p["summary"]["recall"]["mean"] for p in points]
        ys = [p["summary"]["qps"]["mean"] for p in points]
        errs = [p["summary"]["qps"]["stdev"] for p in points]
        ax.errorbar(
            xs, ys, yerr=errs, color=color, marker=marker, markersize=7, linewidth=2,
            markeredgecolor=SURFACE, markeredgewidth=1.5, capsize=0, elinewidth=1,
            label=label(record), zorder=3 if len(points) == 1 else 2,
        )  # fmt: skip
        # Curves converge near recall 1.0, so label them at their high-QPS end, where they are
        # far apart. Single-point baselines are labeled to their right.
        name = f"{record['library']} {record['index'].replace('_', ' ')}"
        if len(points) == 1:
            anchor, offset, align = (xs[0], ys[0]), (7, 0), "left"
        else:
            anchor, offset, align = (xs[0], ys[0]), (0, 9), "center"
        ax.annotate(
            name, anchor, xytext=offset, textcoords="offset points",
            fontsize=8, color=TEXT, ha=align, va="center" if len(points) == 1 else "bottom",
        )  # fmt: skip

    hardware = records[0]["hardware"].get("cpu") or records[0]["hardware"]["machine"]
    ax.set_yscale("log")
    ax.set_xlabel(f"Recall@{k}", color=TEXT)
    ax.set_ylabel("Queries per second (log scale, single thread)", color=TEXT)
    title = f"{dataset}: recall vs. throughput  ·  {hardware}"
    ax.set_title(f"{title}  ·  {title_suffix}" if title_suffix else title, color=TEXT, loc="left")
    ax.grid(True, which="major", color="#e4e3df", linewidth=0.8)
    ax.grid(True, which="minor", color="#efeeea", linewidth=0.5)
    ax.set_axisbelow(True)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    for spine in ("left", "bottom"):
        ax.spines[spine].set_color(MUTED)
    ax.tick_params(colors=MUTED)
    ax.legend(frameon=False, fontsize=8, labelcolor=TEXT, loc="lower left")
    ax.set_xlim(right=1.012)
    ax.margins(y=0.12)
    fig.text(
        0.99, 0.01, f"Up and to the right is better. Generated by {source}",
        ha="right", fontsize=7, color=MUTED,
    )  # fmt: skip
    if note:
        # Above the credit line, so notes never collide with it. Wrapped to the figure width;
        # the plot area shrinks by one line height per wrapped line.
        lines = textwrap.wrap(note, width=150)
        fig.text(0.01, 0.035, "\n".join(lines), ha="left", va="bottom", fontsize=7, color=MUTED)
        fig.tight_layout(rect=(0, 0.035 + 0.022 * len(lines), 1, 1))
    else:
        fig.tight_layout()

    out = out or REPO_ROOT / "results" / "plots" / f"recall_qps_{dataset}.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, facecolor=SURFACE)
    plt.close(fig)
    return str(out.relative_to(REPO_ROOT))


def main() -> int:
    records = latest_records(load_records())
    by_dataset: dict[str, list[dict[str, Any]]] = {}
    for record in records:
        if record["threads"] == 1:
            by_dataset.setdefault(record["dataset"]["name"], []).append(record)
    for dataset, group in sorted(by_dataset.items()):
        dev = any(is_development_machine(r["hardware"]) for r in group)
        note = hardware_note(group[0]["hardware"]) if dev else None
        suffix = "Mac development results, not final" if dev else None
        print("wrote", plot_dataset(dataset, group, note=note, title_suffix=suffix))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
