"""HNSW search throughput at several thread counts (batch queries over the thread pool).

    uv run python bench/run_search_scaling.py --dataset sift1m --threads 1,2,4,8,12,16,32
    uv run python bench/run_search_scaling.py --dataset sift1m --report-only

Each run is one harness process (bench/search_harness.cpp --threads N) on the same index, loaded
from a snapshot built once (data/<dataset>/scaling_index.snap), so runs measure search only.
Thread counts are interleaved across rounds (1,2,4,... then ...,4,2,1) so drift affects each
equally. On Linux each run is pinned with taskset: up to the number of physical cores, to N
distinct physical cores (one hardware thread each), so 1-16 threads never share a core's SMT
sibling; beyond that, to every hardware thread (the SMT point). Writes:

    results/search_scaling/<dataset>/t<threads>-r<round>.json   raw harness output per run
    results/search_scaling/<dataset>/meta.json                   hardware, commit, arguments
    results/search_scaling/scaling_<dataset>.md                  QPS, speedup, efficiency
"""

from __future__ import annotations

import argparse
import json
import platform
import statistics
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from benchmeta import REPO_ROOT, hardware_note, metadata, preflight, thermal_warnings


def physical_core_cpus() -> list[int]:
    """One logical CPU per physical core (the lowest-numbered sibling), from `lscpu -p`."""
    out = subprocess.run(["lscpu", "-p=CPU,CORE,SOCKET"], capture_output=True, text=True)
    first: dict[tuple[str, str], int] = {}
    for line in out.stdout.splitlines():
        if line.startswith("#"):
            continue
        cpu, core, socket = line.split(",")
        first.setdefault((socket, core), int(cpu))
    return sorted(first.values())


def pin_prefix(threads: int) -> tuple[list[str], str]:
    if platform.system() != "Linux":
        return [], "unpinned"
    cores = physical_core_cpus()
    if threads <= len(cores):
        cpus = cores[:threads]
        return ["taskset", "-c", ",".join(map(str, cpus))], f"{threads} physical cores"
    return [], f"all hardware threads ({len(cores)} physical cores, SMT)"


def run(args: argparse.Namespace, out_dir: Path) -> None:
    data = REPO_ROOT / "data" / args.dataset
    metric = json.loads((data / "meta.json").read_text())["metric"]
    snapshot = data / "scaling_index.snap"
    threads = [int(t) for t in args.threads.split(",")]
    base = [
        str(args.build_dir / "bench" / "strata_search"), "--data", str(data),
        "--metric", metric, "--index", "hnsw", "--M", str(args.M),
        "--ef-construction", str(args.ef_construction), "--ef-search", args.ef_search,
        "--runs", str(args.runs), "--snapshot", str(snapshot),
        "--build-threads", str(args.build_threads),
    ]  # fmt: skip
    for r in range(args.rounds):
        order = threads if r % 2 == 0 else list(reversed(threads))
        for t in order:
            out = out_dir / f"t{t}-r{r}.json"
            if out.exists():
                continue  # resume
            preflight(out.name)
            prefix, pinning = pin_prefix(t)
            cmd = [*prefix, *base, "--threads", str(t)]
            print("$", " ".join(cmd), file=sys.stderr, flush=True)
            raw = json.loads(
                subprocess.run(cmd, stdout=subprocess.PIPE, text=True, check=True).stdout
            )
            if raw["build_type"] != "Release" or raw["asserts"]:
                raise SystemExit("harness is not a Release build without asserts")
            raw["pinning"] = pinning
            out.write_text(json.dumps(raw, indent=2) + "\n")
            if warning := thermal_warnings():
                raise SystemExit(f"thermal warning after {out.name}; stopping:\n{warning}")
            time.sleep(args.cooldown)


def report(args: argparse.Namespace, out_dir: Path) -> None:
    meta = json.loads((out_dir / "meta.json").read_text())
    runs: dict[int, list[dict[str, Any]]] = {}
    for path in out_dir.glob("t*-r*.json"):
        raw = json.loads(path.read_text())
        runs.setdefault(raw["threads"], []).append(raw)
    if not runs:
        raise SystemExit(f"no runs in {out_dir}")
    efs = [p["search_params"]["ef_search"] for p in next(iter(runs.values()))[0]["points"]]

    def qps_samples(raws: list[dict[str, Any]], i: int) -> list[float]:
        return [run["qps"] for raw in raws for run in raw["points"][i]["runs"]]

    def recall(raws: list[dict[str, Any]], i: int) -> float:
        return statistics.fmean(run["recall"] for raw in raws for run in raw["points"][i]["runs"])

    lines = [
        f"# HNSW search thread scaling: {args.dataset}",
        "",
        "Generated by `bench/run_search_scaling.py`. Do not edit by hand.",
        "",
        f"- **Hardware:** {hardware_note(meta['hardware'])}",
        f"- Commit: {meta['git']['commit'][:10]}{' (dirty)' if meta['git']['dirty'] else ''}",
        f"- One index (M={args.M}, ef_construction={args.ef_construction}) loaded from a snapshot "
        "for every run; queries spread over the thread pool. QPS mean ± stdev over every run of "
        "every round; speedup and efficiency against 1 thread.",
        "- Pinning per run (Linux): " + "; ".join(
            f"{t} threads: {runs[t][0].get('pinning', 'unpinned')}" for t in sorted(runs)
        ),
        "",
        "| ef_search | recall@10 | threads | QPS | speedup | efficiency |",
        "|---:|---:|---:|---:|---:|---:|",
    ]  # fmt: skip
    for i, ef in enumerate(efs):
        one = statistics.fmean(qps_samples(runs[min(runs)], i))
        for t in sorted(runs):
            samples = qps_samples(runs[t], i)
            mean = statistics.fmean(samples)
            sd = statistics.stdev(samples) if len(samples) > 1 else 0.0
            speedup = mean / one
            lines.append(
                f"| {ef if t == min(runs) else ''} | "
                f"{f'{recall(runs[t], i):.4f}' if t == min(runs) else ''} | {t} | "
                f"{mean:,.0f} ± {sd:,.0f} | {speedup:.2f}x | {speedup / t * min(runs):.0%} |"
            )
    lines.append("")
    table = out_dir.parent / f"scaling_{args.dataset}.md"
    table.write_text("\n".join(lines))
    print(f"wrote {table.relative_to(REPO_ROOT)}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--dataset", default="sift1m")
    parser.add_argument("--threads", default="1,2,4,8,12,16,32")
    parser.add_argument("--rounds", type=int, default=3)
    parser.add_argument("--runs", type=int, default=3, help="runs per harness process")
    parser.add_argument("--M", type=int, default=16)
    parser.add_argument("--ef-construction", type=int, default=200)
    parser.add_argument("--ef-search", default="40,80,160")
    parser.add_argument("--build-threads", type=int, default=16, help="for the one-time build")
    parser.add_argument("--cooldown", type=int, default=10)
    parser.add_argument("--build-dir", type=Path, default=REPO_ROOT / "build" / "release")
    parser.add_argument("--report-only", action="store_true")
    args = parser.parse_args(argv)
    out_dir = REPO_ROOT / "results" / "search_scaling" / args.dataset
    if not args.report_only:
        out_dir.mkdir(parents=True, exist_ok=True)
        if not (out_dir / "meta.json").exists():
            meta = {**metadata(), "args": vars(args)}
            (out_dir / "meta.json").write_text(json.dumps(meta, indent=2, default=str) + "\n")
        run(args, out_dir)
    report(args, out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
