"""HNSW persistence benchmark: build time versus snapshot save and load time.

    uv run python bench/run_hnsw_persist_bench.py --dataset sift1m-200k-q1000 --runs 3

Runs bench/hnsw_persist_bench.cpp once per process, `--runs` times, with a cool-down between
runs and the thermal and busy-machine checks of benchmeta.preflight before each. Each run builds
the index, saves it (durable, atomic), loads it, and checks the loaded index answers every query
identically. Writes:

    results/storage/hnsw_persist-<dataset>-<timestamp>.json   raw runs, metadata, summary
    results/storage/hnsw_persist_<dataset>.md                  table (mean ± stdev)

The snapshot is written under the system temp directory (its filesystem is recorded) and
deleted after each run.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from benchmeta import (
    REPO_ROOT,
    git_info,
    hardware_note,
    metadata,
    preflight,
    thermal_warnings,
    timestamp_slug,
    write_new,
)
from records import summarize_fields

FIELDS = ["build_seconds", "save_seconds", "load_seconds", "file_bytes"]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--dataset", default="sift1m-200k-q1000")
    parser.add_argument("--runs", type=int, default=3)
    parser.add_argument("--M", type=int, default=16)
    parser.add_argument("--ef-construction", type=int, default=200)
    parser.add_argument("--cooldown", type=int, default=60)
    parser.add_argument("--build-dir", type=Path, default=REPO_ROOT / "build" / "release")
    args = parser.parse_args(argv)

    binary = args.build_dir / "bench" / "strata_hnsw_persist_bench"
    snapshot = Path(tempfile.gettempdir()) / "strata_hnsw_persist.snap"
    cmd = [
        str(binary), "--data", str(REPO_ROOT / "data" / args.dataset), "--out", str(snapshot),
        "--M", str(args.M), "--ef-construction", str(args.ef_construction),
    ]  # fmt: skip
    if git_info()["dirty"]:
        print("warning: uncommitted changes; the record will say so", file=sys.stderr)
    runs = []
    for i in range(args.runs):
        preflight(f"run {i + 1}")
        print("$", " ".join(cmd), file=sys.stderr, flush=True)
        raw = json.loads(subprocess.run(cmd, stdout=subprocess.PIPE, text=True, check=True).stdout)
        if raw["asserts"]:
            print("error: built with asserts; use the release preset", file=sys.stderr)
            return 1
        if not raw["results_identical"]:
            print("error: the loaded index answered differently", file=sys.stderr)
            return 1
        runs.append(raw)
        print(
            f"run {i + 1}: build {raw['build_seconds']:.2f} s, save {raw['save_seconds']:.3f} s, "
            f"load {raw['load_seconds']:.3f} s",
            file=sys.stderr,
            flush=True,
        )
        if warning := thermal_warnings():
            print(f"thermal warning after run {i + 1}; stopping:\n{warning}", file=sys.stderr)
            break
        if i + 1 < args.runs:
            time.sleep(args.cooldown)

    df = subprocess.run(["df", "-P", str(snapshot.parent)], capture_output=True, text=True)
    summary = summarize_fields(runs, FIELDS)
    record = {
        **metadata(),
        "dataset": args.dataset,
        "command": cmd,
        "filesystem": df.stdout.strip().splitlines()[-1] if df.returncode == 0 else "",
        "runs": runs,
        "summary": summary,
    }
    out = REPO_ROOT / "results" / "storage" / f"hnsw_persist-{args.dataset}-{timestamp_slug()}.json"
    write_new(out, json.dumps(record, indent=2) + "\n")
    print(f"saved {out.relative_to(REPO_ROOT)}")

    def cell(field: str, scale: float = 1.0, digits: int = 2) -> str:
        s = summary[field]
        return f"{s['mean'] * scale:.{digits}f} ± {s['stdev'] * scale:.{digits}f}"

    build, load = summary["build_seconds"]["mean"], summary["load_seconds"]["mean"]
    lines = [
        f"# HNSW snapshot save/load vs. rebuild: {args.dataset}",
        "",
        "Generated by `bench/run_hnsw_persist_bench.py`. Do not edit by hand.",
        "",
        f"- **Hardware:** {hardware_note(record['hardware'])}",
        f"- Commit: {record['git']['commit'][:10]}{' (dirty)' if record['git']['dirty'] else ''}",
        f"- {runs[0]['num_base']:,} vectors x {runs[0]['dim']} dims, M={args.M}, "
        f"ef_construction={args.ef_construction}; {len(runs)} runs, one process each, "
        f"{args.cooldown} s cool-down; mean ± stdev.",
        "- Save is a durable, atomic snapshot write (temp file, fsync, rename, directory fsync).",
        "  Load reads, checksums, and validates the file. Every run checked that the loaded index "
        "answers all queries identically.",
        f"- Snapshot filesystem: `{record['filesystem']}`",
        "",
        "| step | seconds |",
        "|---|---:|",
        f"| build (single thread) | {cell('build_seconds')} |",
        f"| save | {cell('save_seconds', digits=3)} |",
        f"| load | {cell('load_seconds', digits=3)} |",
        "",
        f"Snapshot size: {summary['file_bytes']['mean'] / 2**20:.1f} MiB. "
        f"Loading is **{build / load:.0f}x faster** than rebuilding.",
        "",
    ]
    table = REPO_ROOT / "results" / "storage" / f"hnsw_persist_{args.dataset}.md"
    table.write_text("\n".join(lines))
    print(f"wrote {table.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
