"""HNSW build time at several thread counts, with graph quality at each.

    uv run python bench/run_hnsw_build_scaling.py --dataset sift1m-200k-q1000 --threads 1,2,4
    uv run python bench/run_hnsw_build_scaling.py --dataset sift1m-200k-q1000 --report-only

Each run is one harness process (bench/search_harness.cpp --build-threads N): build the index,
then a short ef_search sweep for recall, plus the harness's graph statistics (layer-0
reachability, mean degree). Thread counts are interleaved across rounds (1,2,4 then 4,2,1, ...)
so slow drift such as throttling affects each equally. Before every run the machine must be cool
and otherwise idle (benchmeta.preflight); a thermal warning after any run stops the sweep and
keeps what finished. Writes:

    results/hnsw_build/<dataset>/t<threads>-r<round>.json   raw harness output per run
    results/hnsw_build/<dataset>/meta.json                   hardware, commit, arguments
    results/hnsw_build/build_scaling_<dataset>.md            build time, speedup, quality

On the fanless M2 these numbers are indicative; the full 1-16 thread curve comes from the AWS
session.
"""

from __future__ import annotations

import argparse
import json
import statistics
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from benchmeta import REPO_ROOT, git_info, hardware_note, metadata, preflight, thermal_warnings

OUT_ROOT = REPO_ROOT / "results" / "hnsw_build"


def run(args: argparse.Namespace, out_dir: Path) -> None:
    threads = [int(t) for t in args.threads.split(",")]
    harness = args.build_dir / "bench" / "strata_search"
    for r in range(args.rounds):
        for t in threads if r % 2 == 0 else threads[::-1]:
            path = out_dir / f"t{t}-r{r}.json"
            if path.exists():
                continue  # resume an interrupted sweep
            preflight(path.name)
            cmd = [
                str(harness), "--data", str(REPO_ROOT / "data" / args.dataset), "--index", "hnsw",
                "--M", str(args.M), "--ef-construction", str(args.ef_construction),
                "--build-threads", str(t), "--ef-search", args.ef_search, "--runs", "1",
            ]  # fmt: skip
            print(f"round {r}: {t} build threads", file=sys.stderr, flush=True)
            raw = json.loads(subprocess.run(cmd, capture_output=True, text=True, check=True).stdout)
            if raw["build_type"] != "Release" or raw["asserts"]:
                raise SystemExit("harness is not a Release build without asserts")
            path.write_text(json.dumps(raw, indent=2) + "\n")
            print(f"  built in {raw['build_seconds']:.2f} s", file=sys.stderr, flush=True)
            if warning := thermal_warnings():
                raise SystemExit(f"thermal warning after {path.name}; stopping:\n{warning}")
            time.sleep(args.cooldown)


def spread(values: list[float], digits: int) -> str:
    sd = statistics.stdev(values) if len(values) > 1 else 0.0
    return f"{statistics.fmean(values):.{digits}f} ± {sd:.{digits}f}"


def report(args: argparse.Namespace, out_dir: Path, meta: dict[str, Any]) -> None:
    # Settings as the measured runs used them (meta.json), not this invocation's defaults.
    run_args = meta.get("args", {})
    graph_m = run_args.get("M", args.M)
    ef_construction = run_args.get("ef_construction", args.ef_construction)
    cooldown = run_args.get("cooldown", args.cooldown)
    by_threads: dict[int, list[dict[str, Any]]] = {}
    for path in sorted(out_dir.glob("t*-r*.json")):
        t = int(path.stem.split("-")[0][1:])
        by_threads.setdefault(t, []).append(json.loads(path.read_text()))
    if not by_threads:
        raise SystemExit("no runs to report")
    efs = [p["search_params"]["ef_search"] for p in next(iter(by_threads.values()))[0]["points"]]
    base = statistics.fmean(r["build_seconds"] for r in by_threads.get(1, []) or [{}])
    git = meta["git"]
    lines = [
        f"# HNSW build scaling: {args.dataset}",
        "",
        "Generated by `bench/run_hnsw_build_scaling.py`. Do not edit by hand.",
        "",
        f"- **Hardware:** {hardware_note(meta['hardware'])}",
        "- **Indicative only:** the M2 has 4 performance cores and no fan; the full 1-16 thread "
        "curve comes from the AWS session (Phase 9).",
        f"- Commit: {git['commit'][:10]}{' (dirty)' if git['dirty'] else ''}",
        f"- M={graph_m}, ef_construction={ef_construction}; runs interleaved across thread "
        f"counts, {cooldown} s cool-down between runs; mean ± stdev over runs. 1 thread is "
        "the sequential, deterministic build; more threads use the parallel add_batch.",
        "- Quality per run: recall@10 (tie-aware, against exact ground truth) from one search pass "
        "per ef_search; layer-0 reachability from the entry point; mean layer-0 out-degree.",
        "",
        "| build threads | runs | build seconds | speedup vs 1 | "
        + " | ".join(f"recall ef={ef}" for ef in efs)
        + " | reachable | mean degree |",
        "|---:|---:|---:|---:|" + "---:|" * len(efs) + "---:|---:|",
    ]
    for t in sorted(by_threads):
        runs = by_threads[t]
        secs = [r["build_seconds"] for r in runs]
        speedup = f"{base / statistics.fmean(secs):.2f}x" if 1 in by_threads else "—"
        recalls = [
            spread([r["points"][i]["runs"][0]["recall"] for r in runs], 4) for i in range(len(efs))
        ]
        reach = spread([r["graph"]["layer0_reachable_fraction"] for r in runs], 4)
        degree = spread([r["graph"]["layer0_mean_degree"] for r in runs], 2)
        lines.append(
            f"| {t} | {len(runs)} | {spread(secs, 2)} | {speedup} | "
            + " | ".join(recalls)
            + f" | {reach} | {degree} |"
        )
    lines.append("")
    out = OUT_ROOT / f"build_scaling_{out_dir.name}.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(REPO_ROOT)}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--dataset", default="sift1m-200k-q1000")
    parser.add_argument("--threads", default="1,2,4")
    parser.add_argument("--rounds", type=int, default=3)
    parser.add_argument("--M", type=int, default=16)
    parser.add_argument("--ef-construction", type=int, default=200)
    parser.add_argument("--ef-search", default="10,40,160")
    parser.add_argument("--cooldown", type=int, default=60)
    parser.add_argument("--build-dir", type=Path, default=REPO_ROOT / "build" / "release")
    parser.add_argument("--report-only", action="store_true")
    parser.add_argument(
        "--label",
        help="keep this machine's runs and report apart (results/.../<dataset>-<label>): the "
        "runner resumes by skipping runs whose files exist, so runs from another machine in the "
        "same folder would be silently reused",
    )
    args = parser.parse_args(argv)

    name = f"{args.dataset}-{args.label}" if args.label else args.dataset
    out_dir = OUT_ROOT / name
    out_dir.mkdir(parents=True, exist_ok=True)
    meta_path = out_dir / "meta.json"
    if meta_path.exists():
        meta = json.loads(meta_path.read_text())
    else:
        if git_info()["dirty"]:
            print("warning: uncommitted changes; the record will say so", file=sys.stderr)
        meta = {**metadata(), "args": {k: str(v) for k, v in vars(args).items()}}
        meta_path.write_text(json.dumps(meta, indent=2) + "\n")
    if not args.report_only:
        run(args, out_dir)
    report(args, out_dir, meta)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
