"""Interleaved A/B comparison of two strata_search builds on one dataset (HNSW sweep).

    uv run python bench/run_ab_search.py --name prefetch \\
        --a /path/to/strata_search_before --a-label before --a-commit 7232d6e \\
        --b build/release/bench/strata_search --b-label after

Runs the two binaries alternately (A B, B A, A B, ...), so slow drift such as thermal throttling
on the fanless M2 affects both equally. Each run is a separate process: build the index, then sweep
ef_search with --runs timed passes per point. Writes:

    results/ab/<name>/<label>-pair<i>.json   raw harness output per run
    results/ab/<name>/meta.json              hardware, commits, arguments
    results/ab/<name>/b.patch                B's diff against its commit, if B was uncommitted
    results/ab/<name>.md                     per-ef QPS (mean, stdev, range across runs), paired
                                             B/A ratios, and a check that recall is identical

Safeguards: before every run, refuses to start on a thermal warning (`pmset -g therm`, macOS) or
while another process is busy; checks the thermal state again after; stops at the first problem,
keeping what finished. A cool-down separates runs.
"""

from __future__ import annotations

import argparse
import json
import statistics
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from benchmeta import REPO_ROOT, git_info, hardware_note, metadata, preflight, thermal_warnings

OUT_ROOT = REPO_ROOT / "results" / "ab"


def run_harness(binary: str, args: argparse.Namespace) -> dict[str, Any]:
    cmd = [
        binary, "--data", str(REPO_ROOT / "data" / args.dataset), "--index", "hnsw",
        "--M", str(args.M), "--ef-construction", str(args.ef_construction),
        "--ef-search", args.ef_search, "--runs", str(args.runs),
    ]  # fmt: skip
    proc = subprocess.run(cmd, capture_output=True, text=True, check=True)
    raw: dict[str, Any] = json.loads(proc.stdout)
    if raw["build_type"] != "Release" or raw["asserts"]:
        raise SystemExit(f"{binary} is not a Release build without asserts")
    return raw


def run(args: argparse.Namespace, out_dir: Path) -> None:
    order = [("a", args.a, args.a_label), ("b", args.b, args.b_label)]
    for pair in range(args.pairs):
        # Alternate which binary goes first, so neither always runs on a cooler machine.
        for _, binary, label in order if pair % 2 == 0 else order[::-1]:
            path = out_dir / f"{label}-pair{pair}.json"
            if path.exists():
                continue  # resume an interrupted comparison
            preflight(path.name)
            print(f"pair {pair}: {label}", file=sys.stderr, flush=True)
            raw = run_harness(binary, args)
            path.write_text(json.dumps(raw, indent=2) + "\n")
            if warning := thermal_warnings():
                raise SystemExit(f"thermal warning after {path.name}; stopping:\n{warning}")
            time.sleep(args.cooldown)


def point_means(raw: dict[str, Any]) -> dict[int, dict[str, float]]:
    """Per ef_search: mean QPS over this process's timed passes, and its (single) recall."""
    out = {}
    for point in raw["points"]:
        recalls = {r["recall"] for r in point["runs"]}
        assert len(recalls) == 1, "recall varies between passes of one build"
        out[point["search_params"]["ef_search"]] = {
            "qps": statistics.fmean(r["qps"] for r in point["runs"]),
            "recall": recalls.pop(),
        }
    return out


def spread(values: list[float]) -> str:
    mean = statistics.fmean(values)
    sd = statistics.stdev(values) if len(values) > 1 else 0.0
    return (
        f"{mean:,.0f} ± {sd:,.0f} ({100 * sd / mean:.1f}%), "
        f"range {min(values):,.0f} to {max(values):,.0f}"
    )


def report(args: argparse.Namespace, out_dir: Path, meta: dict[str, Any]) -> None:
    runs = {
        label: [json.loads(p.read_text()) for p in sorted(out_dir.glob(f"{label}-pair*.json"))]
        for label in (args.a_label, args.b_label)
    }
    pairs = min(len(runs[args.a_label]), len(runs[args.b_label]))
    if pairs == 0:
        raise SystemExit("no complete pairs to report")
    a = [point_means(r) for r in runs[args.a_label][:pairs]]
    b = [point_means(r) for r in runs[args.b_label][:pairs]]
    efs = sorted(a[0])

    lines = [
        f"# A/B: {args.b_label} vs {args.a_label} on {args.dataset}",
        "",
        "Generated by `bench/run_ab_search.py`. Do not edit by hand.",
        "",
        f"- **Hardware:** {hardware_note(meta['hardware'])}",
        f"- A = `{args.a_label}` at {meta['a_commit']}; B = `{args.b_label}` at {meta['b_commit']}"
        + (" plus `b.patch` (uncommitted when measured)" if meta["b_dirty"] else ""),
        f"- {pairs} interleaved pairs (order alternates each pair), {args.cooldown} s cool-down "
        f"between runs. Each run is a fresh process: build (M={args.M}, "
        f"ef_construction={args.ef_construction}), then {args.runs} timed passes per ef_search "
        "over all queries, single thread.",
        "- QPS per run = mean of its timed passes. The spread is across runs (processes), which "
        "includes thermal drift. Ratio = B / A within each pair.",
        "",
        "| ef_search | recall@10 (A = B?) | QPS A | QPS B | B / A mean | B / A range |",
        "|---:|---:|---|---|---:|---:|",
    ]
    all_recall_equal = True
    for ef in efs:
        recalls = {m[ef]["recall"] for m in a + b}
        equal = len(recalls) == 1
        all_recall_equal &= equal
        ratios = [bb[ef]["qps"] / aa[ef]["qps"] for aa, bb in zip(a, b, strict=True)]
        recall_text = f"{recalls.pop():.4f} (identical)" if equal else f"DIFFERS: {sorted(recalls)}"
        lines.append(
            f"| {ef} | {recall_text} | {spread([m[ef]['qps'] for m in a])} "
            f"| {spread([m[ef]['qps'] for m in b])} | {statistics.fmean(ratios):.3f} "
            f"| {min(ratios):.3f} to {max(ratios):.3f} |"
        )
    build_a = [r["build_seconds"] for r in runs[args.a_label][:pairs]]
    build_b = [r["build_seconds"] for r in runs[args.b_label][:pairs]]
    build_ratios = [bb / aa for aa, bb in zip(build_a, build_b, strict=True)]
    graphs_equal = all(
        ra["graph"] == rb["graph"]
        for ra, rb in zip(runs[args.a_label][:pairs], runs[args.b_label][:pairs], strict=True)
    )
    lines += [
        "",
        f"Build seconds: A {statistics.fmean(build_a):.1f} ± {statistics.stdev(build_a):.1f}, "
        f"B {statistics.fmean(build_b):.1f} ± {statistics.stdev(build_b):.1f}; "
        f"B / A mean {statistics.fmean(build_ratios):.3f}, range "
        f"{min(build_ratios):.3f} to {max(build_ratios):.3f}.",
        "",
        f"Recall identical at every ef_search in every run: **{all_recall_equal}**. "
        f"Graph statistics identical: **{graphs_equal}**.",
        "",
    ]
    out = OUT_ROOT / f"{args.name}.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(REPO_ROOT)}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--name", required=True, help="results/ab/<name>")
    parser.add_argument("--dataset", default="sift1m-200k-q1000")
    parser.add_argument("--a", required=True, help="baseline strata_search binary")
    parser.add_argument("--a-label", default="before")
    parser.add_argument("--a-commit", required=True, help="commit the A binary was built from")
    parser.add_argument("--b", default=str(REPO_ROOT / "build/release/bench/strata_search"))
    parser.add_argument("--b-label", default="after")
    parser.add_argument("--pairs", type=int, default=5)
    parser.add_argument("--runs", type=int, default=5, help="timed passes per ef per run")
    parser.add_argument("--M", type=int, default=16)
    parser.add_argument("--ef-construction", type=int, default=200)
    parser.add_argument("--ef-search", default="10,20,40,80,160,320")
    parser.add_argument("--cooldown", type=int, default=60)
    parser.add_argument("--report-only", action="store_true")
    args = parser.parse_args(argv)

    out_dir = OUT_ROOT / args.name
    out_dir.mkdir(parents=True, exist_ok=True)
    meta_path = out_dir / "meta.json"
    if meta_path.exists():
        meta = json.loads(meta_path.read_text())
    else:
        git = git_info()
        meta = {
            **metadata(),
            "a_commit": args.a_commit,
            "b_commit": git["commit"][:10],
            "b_dirty": git["dirty"],
            "args": vars(args),
        }
        if git["dirty"]:
            patch = subprocess.run(
                ["git", "-C", str(REPO_ROOT), "diff", "HEAD", "--", ".", ":!results"],
                capture_output=True, text=True, check=True,
            ).stdout  # fmt: skip
            (out_dir / "b.patch").write_text(patch)
        meta_path.write_text(json.dumps(meta, indent=2) + "\n")
    if not args.report_only:
        run(args, out_dir)
    report(args, out_dir, meta)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
