"""Generate src/text/emoji_table.inc (Unicode Emoji=Yes ranges) from emoji-data.txt.

    uv run python scripts/gen_emoji_table.py

The tokenizer emits emoji as their own tokens, as Lucene's StandardTokenizer does. ASCII code
points with Emoji=Yes (digits, '#', '*') are excluded: on their own they are ordinary characters.
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

URL = "https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt"
OUT = Path(__file__).resolve().parent.parent / "src" / "text" / "emoji_table.inc"


def main() -> int:
    request = urllib.request.Request(URL, headers={"User-Agent": "strata/0.1"})
    text = urllib.request.urlopen(request).read().decode()
    version = re.search(r"# Version: ([\d.]+)", text)
    ranges: list[tuple[int, int]] = []
    for line in text.splitlines():
        m = re.match(r"([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*Emoji\s*#", line)
        if m:
            lo, hi = int(m.group(1), 16), int(m.group(2) or m.group(1), 16)
            lo = max(lo, 0x80)
            if lo <= hi:
                ranges.append((lo, hi))
    ranges.sort()
    merged: list[list[int]] = []
    for lo, hi in ranges:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], hi)
        else:
            merged.append([lo, hi])
    lines = [
        "// Generated by scripts/gen_emoji_table.py from",
        f"// {URL} (version {version.group(1) if version else 'unknown'}). Do not edit.",
        "// Emoji=Yes ranges, excluding ASCII.",
        "",
        f"constexpr std::array<std::pair<char32_t, char32_t>, {len(merged)}> kEmojiRanges = {{{{",
    ]
    lines += [f"    {{0x{lo:X}, 0x{hi:X}}}," for lo, hi in merged]
    lines += ["}};", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(merged)} ranges)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
